name: Run Tests

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/**'

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        java-version: [ 21, 24 ]

    runs-on: ubuntu-latest
    name: Test on Java ${{ matrix.java-version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Tests with Coverage
        run: make test

      - name: Upload Coverage Report to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./target/site/jacoco/jacoco.xml
          fail_ci_if_error: false
